# Generated by Django 5.2.4 on 2025-08-14 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_company_description_user_founder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='connections',
            field=models.ManyToManyField(related_name='connected_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
