# Generated by Django 5.2.4 on 2025-08-14 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_industries', models.JSONField(default=list)),
                ('investment_stage', models.JSONField(default=list)),
                ('min_investment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_investment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target_markets', models.JSONField(default=list)),
                ('risk_appetite', models.IntegerField(default=5)),
                ('expected_return', models.FloatField()),
                ('investment_timeline', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Investor preferences',
            },
        ),
        migrations.CreateModel(
            name='StartupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=100)),
                ('funding_stage', models.CharField(max_length=50)),
                ('target_market', models.CharField(max_length=100)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('growth_rate', models.FloatField()),
                ('team_size', models.IntegerField()),
                ('technological_innovation', models.IntegerField()),
                ('market_size', models.DecimalField(decimal_places=2, max_digits=15)),
                ('competition_level', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='startup_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Startup profiles',
            },
        ),
        migrations.CreateModel(
            name='AIMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility_score', models.FloatField()),
                ('ai_analysis', models.TextField(blank=True, null=True)),
                ('match_explanation', models.TextField(blank=True, null=True)),
                ('suggestion_type', models.CharField(max_length=50)),
                ('confidence_score', models.FloatField()),
                ('factor_breakdown', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_investor_matches', to=settings.AUTH_USER_MODEL)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_startup_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'AI Matches',
                'unique_together': {('investor', 'startup')},
            },
        ),
    ]
