# Generated by Django 5.2.4 on 2025-08-14 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('first_contact_date', models.DateField()),
                ('last_interaction_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('proposed_valuation', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deal_flow', to=settings.AUTH_USER_MODEL)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_deals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_interaction_date'],
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_sector', models.CharField(max_length=100)),
                ('investment_stage', models.CharField(max_length=50)),
                ('risk_level', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('invested_date', models.DateField()),
                ('initial_investment', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('ownership_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('roi_percentage', models.DecimalField(decimal_places=2, max_digits=7)),
                ('last_round', models.CharField(max_length=50)),
                ('next_milestone', models.CharField(max_length=200)),
                ('performance_status', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-invested_date'],
            },
        ),
        migrations.CreateModel(
            name='MarketUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('sector', models.CharField(max_length=100)),
                ('impact_level', models.CharField(max_length=50)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('source_url', models.URLField(blank=True)),
                ('relevant_startups', models.ManyToManyField(related_name='relevant_market_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target_date', models.DateField()),
                ('achieved_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('impact_description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['target_date'],
            },
        ),
        migrations.CreateModel(
            name='StartupMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=15)),
                ('burn_rate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('runway_months', models.IntegerField()),
                ('team_size', models.IntegerField()),
                ('customer_count', models.IntegerField()),
                ('churn_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('growth_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('market_size', models.DecimalField(decimal_places=2, max_digits=15)),
                ('last_funding_date', models.DateField()),
                ('last_funding_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('current_valuation', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Startup metrics',
            },
        ),
    ]
